# Generated by Django 4.2.5 on 2023-11-23 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10)),
                ('birth', models.DateField()),
                ('phone', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
            ],
        ),
    ]
