# Generated by Django 4.2.5 on 2023-11-23 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='birth',
            field=models.DateField(default=datetime.date.today, verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='gender',
            field=models.CharField(choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10, verbose_name='성별'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='name',
            field=models.CharField(max_length=10, verbose_name='이름'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='password',
            field=models.CharField(max_length=30, verbose_name='비밀번호'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='phone',
            field=models.CharField(max_length=10, verbose_name='연락처'),
        ),
        migrations.AlterField(
            model_name='signup',
            name='user_id',
            field=models.CharField(max_length=30, verbose_name='아이디'),
        ),
    ]
