# Generated by Django 4.2.5 on 2023-11-23 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_signup_birth_alter_signup_gender_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
